### ISSUE TITLE
Cannot upload files to brick

### ISSUE THREAD

**Issue by stachir** [ev3dev/vscode-ev3dev-browser#124]
**Describe the bug**
During upload the VS Code shows uploading first file in a list indefinitely.

**Expected behavior**
Upload all files in project and the program starts at brick

**Desktop (please complete the following information):**
Visual Studio Code
Version: 1.123.2 (system setup)
Commit: 3c631b164c239e7aeaaae7c626b46c527b361af2
Date: 2026-06-09T15:06:40-07:00
Electron: 42.2.0
ElectronBuildId: 14159160
Chromium: 148.0.7778.97
Node.js: 24.15.0
V8: 14.8.178.14-electron.0

OS: Windows_NT x64 10.0.19045

**Additional context**
Worked in Visual Studio Code version 1.120

Here are logs:

```
2026-06-10 11:28:15.823 [error] TypeError: rc is not a function
	at zn (c:\Users\user\.vscode\extensions\ev3dev.ev3dev-browser-1.2.1\out\main.js:28:33485)
	at ne.fsetstat (c:\Users\user\.vscode\extensions\ev3dev.ev3dev-browser-1.2.1\out\main.js:28:22306)
	at ne.fchmod (c:\Users\user\.vscode\extensions\ev3dev.ev3dev-browser-1.2.1\out\main.js:28:23168)
	at c:\Users\user\.vscode\extensions\ev3dev.ev3dev-browser-1.2.1\out\main.js:28:13158
	at ne._transform (c:\Users\user\.vscode\extensions\ev3dev.ev3dev-browser-1.2.1\out\main.js:28:6845)
	at Transform._write (node:internal/streams/transform:171:8)
	at writeOrBuffer (node:internal/streams/writable:570:12)
	at _write (node:internal/streams/writable:499:10)
	at Writable.write (node:internal/streams/writable:508:10)
	at Bt.ondata (node:internal/streams/readable:1012:24)
	at Bt.emit (node:events:509:28)
	at addChunk (node:internal/streams/readable:563:12)
	at readableAddChunkPushByteMode (node:internal/streams/readable:514:3)
	at Readable.push (node:internal/streams/readable:394:5)
	at te.<anonymous> (c:\Users\user\.vscode\extensions\ev3dev.ev3dev-browser-1.2.1\out\main.js:37:29394)
	at te.emit (node:events:509:28)
	at Ip (c:\Users\user\.vscode\extensions\ev3dev.ev3dev-browser-1.2.1\out\main.js:37:6708)
	at te._transform (c:\Users\user\.vscode\extensions\ev3dev.ev3dev-browser-1.2.1\out\main.js:33:6129)
	at Transform._write (node:internal/streams/transform:171:8)
	at writeOrBuffer (node:internal/streams/writable:570:12)
	at _write (node:internal/streams/writable:499:10)
	at Writable.write (node:internal/streams/writable:508:10)
	at Socket.ondata (node:internal/streams/readable:1012:24)
	at Socket.emit (node:events:509:28)
	at addChunk (node:internal/streams/readable:563:12)
	at readableAddChunkPushByteMode (node:internal/streams/readable:514:3)
	at Readable.push (node:internal/streams/readable:394:5)
	at TCP.onStreamRead (node:internal/stream_base_commons:189:23)
```

**Comment by kennywest** [comment]
I think I have the same problem, but on an even more recent version of vscode (I have 1.142.2). This is on windows 11. I can connect to the ev3 brick, I can also ssh into it. Using normal winscp I can also upload files into it. But I cannot upload anything from the ev3 browser extension.
I have no idea where I can find logs for this, if you can point me to a location, I will be happy to provide them.
Also tried to build and use this branch mentioned here -> https://github.com/ev3dev/vscode-ev3dev-browser/issues/126
Same problem.

The strange thing is, when I use the same version of vscode on Mac OS (sonoma), all works fine. So I can connect with the brick and can upload files without any problems.

Any help here is very much appreciated.
Thank you.

**Comment by AlyssonNeves** [comment]
@dlech  , please resolve this as soon as possible.

**Comment by AlyssonNeves** [comment]
@kennywest, you said:

> I also tried to build and use the branch mentioned here:
> https://github.com/ev3dev/vscode-ev3dev-browser/issues/126
> Same problem.

I tried it as well, but the problem is still occurring.

**Comment by AlyssonNeves** [comment]
@stachir , @kennywest , this issue was fixed today, June 22, 2026, in version 1.2.2:

https://github.com/ev3dev/vscode-ev3dev-browser/issues/126

The new version is now available in the VS Code Marketplace:

https://marketplace.visualstudio.com/items?itemName=ev3dev.ev3dev-browser

Thank you very much, @dlech . It’s working again.
